name: Test workflow SEO

on:
  push:
    branches: [seo-quick-fixes-2026-08-15]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo OK
